# Site settings
title: Jacob Callear
email: spamj@callear.net
url: https://github.com/jeromelachaud/freelancer-theme
description: "Jacob Callear | Project Showcase | Data Engineer"
keywords: "data engineer, python, sql, aws, engineering, "
skills: "Data Engineer | Python - SQL - AWS |"
meta_author: Jacob Callear

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F5A25D
  primary-rgb: "245,162,93"
  secondary: 389393
  secondary-dark: 389393

# Footer settings
footer:
  copyright: Jacob Callear
  location: Location
  social: Links
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://uk.linkedin.com/in/jacob-callear
  - title: github
    url: https://github.com/jacobcallear

# Postal address (add as many lines as necessary)
address:
  - line: Dudley
  - line: West Midlands
  - line: UK

# Credits content
credits: 'Freelancer is an open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
